version: '3'
services:
  mongo:
    image: mongo:4.0.8
    container_name: renaper_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: renaper
      MONGO_INITDB_ROOT_PASSWORD: renaper
      MONGO_INITDB_DATABASE: renaper
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27018:27017"
  api:
    container_name: renaper_api
    build: .
    ports:
      - "5001:5000"
    environment:
      APP_ENV: "prod"
      APP_DEBUG: "False"
      APP_PORT: 5000
      MONGODB_DATABASE: renaper
      MONGODB_USERNAME: renaper
      MONGODB_PASSWORD: renaper
      MONGODB_HOSTNAME: mongo
      FLASK_ENV: development
      PAQUETE1_API_KEY: ''
      PAQUETE2_API_KEY: ''
      PAQUETE3_API_KEY: ''
      USERNAME: ""
      PASSWORD: ""
    volumes:
      - .:/code
    depends_on:
      - mongo
volumes:
  mongo-data:
  mongo-configdb: